# Contents

- [4.1.1 초난감 예외처리](#411-초난감-예외처리)
- [4.1.2 예외의 종류와 특징](#412-예외의-종류와-특징)
- [4.1.3 예외처리 방법](#413-예외처리-방법)
- [4.1.4 예외처리 전략](#414-예외처리-전략)
- [4.1.5 SQLException은 어떻게 됐나?](#415-SQLException은-어떻게-됐나)

# 4.1 사라진 SQLException

3장에서 `JdbcTemplate`을 적용하면서 `deleteAll()` 메서드의 예외 처리를 지웠었다.

```java
public class UserDao {
    // ...
    public void deleteAll() { // 에외 처리를 하지 않고 있다.
        this.jdbcTemplate.update("delete from users");
    }
    // ...
}
```

`SQLException`은 `JDBC API`의 메서드들이 던지는 것이므로 당연히 있어야 하는데 어디로 간 것일까?

## 4.1.1 초난감 예외처리

먼저 개발자들의 코드에서 종종 발견되는 난감한 예외처리 방법을 알아보자.

### 예외 블랙홀

```java
try {
    // ...
} catch (SQLException e) {
}
```

위와 같이 `try/catch` 블럭으로 예외를 잡고 있지만 처리는 하지 않고 있다. 아무것도 하지 않고 넘어가는 것은 정말 위험한 일이다. 프로그램 실행 중에 어디선가 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다. 결국 발생한 예외로 인해 예상치 못한 다른 문제를 일으킬 것이다. 아래과 같은 코드도 마찬가지로 위험한 코드다.

```java
try {
    // ...
} catch (SQLException e) {
    System.out.println(e);
}

try {
    // ...
} catch (SQLException e) {
    e.printStackTrace();
}
```

예외가 발생하였을 때 화면에 출력만 하는 것은 문제가 있다. 콘솔 로그를 누군가가 계속 모니터링하지 않는 한 이 예외 코드는 처리되지 않을 것이다.

예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지다. 모든 예외는 적절하게 복구되든지, 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보되어야 한다.

굳이 예외를 잡아서 조치를 취할 방법이 없다면 잡지 말고 메서드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가하는 것이 낫다.

### 무의미하고 무책임한 throws

```java
public void method1() throws Exception {
    method2();
    // ...
}

public void method2() throws Exception {
    method3();
    // ...
}

public void method3() throws Exception {
    // ...
}
```

위와 같이 메서드 선언에 `throws Exception`을 기계적으로 붙이는 것도 문제가 된다. 자신이 사용하려고 하는 메서드에 `throws Exception`이 선언되어 있다고 가정해보자. 이러한 메서드 선언에는 의미 있는 정보를 얻을 수 없다. 정말 실행 중에 예외적인 상황이 발생할 수 있다는 것인지, 그냥 습관적으로 복사해서 붙여놓은 것인지 알 수 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다.

## 4.1.2 예외의 종류와 특징

예외처리에 관해서는 자바 개발자들 사이에서도 오랫동안 많은 논쟁이 있었는데, 가장 큰 이슈는 `체크 예외(checked exception)`라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.

자바에서 `throw`를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

#### Error

`java.lang.Error` 클래스의 서브클래스들이다. `에러`는 시스템에 비정상적인 상황이 발생했을 경우에 사용된다. 애플리케이션 코드에서 잡으려고 해봤자 아무런 대응 방법이 없다. 따라서 시스템 레벨에서 특별한 작업을 하는 것이 아니라면 애플리케이션에서는 이런 `에러`에 대한 처리는 신경쓰지 말자.

#### Exception과 체크 예외

`java.lang.Exception` 클래스와 그 서브클래스로 정의되는 예외들은 `에러`와 달리 개발자들이 만든 애플리케이션 코드와 작업 중에 예외상황이 발생했을 경우에 사용된다. `Exception` 클래스는 다시 `체크 예외`와 `언체크 예외(unchecked exception)`로 구분되며, `체크 예외`는 `Exception` 클래스의 서브클래스이면서 `RuntimeException` 클래스를 상속하지 않은 것들이고, `언체크 예외`는 `RuntimeException`을 상속한 클래스들을 말한다.

일반적으로 예외라고 하면 `체크 예외`라고 생각해도 된다. `체크 예외`가 발생할 수 있는 메서드를 사용할 경우 `catcy` 문으로 잡든지, 다시 `throws`를 정의해서 메서드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

#### RuntimeException과 언체크/런타임 예외

`java.lang.RuntimeException` 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 `언체크 예외`라고 불린다. 또는 `런타임 예외`라고도 한다. `에러`와 마찬가지로 `catch` 문으로 잡거나 `throws`로 선언하지 않아도 된다.

`런타임 예외`는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이며 대표적으로 `NullPointerException`, `IllegalArgumentException` 등이 있다.

## 4.1.3 예외처리 방법

예외를 처리하는 일반적인 방법을 알아보자.

### 예외 복구

첫 번째 예외 처리 방법은 예외상황을 파악하고 문제를 해결해서 복구하는 것이다.

예를 들어 사용자가 파일을 읽으려고 시도했는데 해당 파일이 없거나 다른 문제가 있어서 읽히지가 않아서 `IOException`이 발 생했다고 가정해보자. 이때는 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내해서 예외상황을 해결할 수 있다. 이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다. 단, `IOException` 에러 메시지가 사용자에게 그냥 던져지는 것은 예외 복구라고 할 수 없다.

네트워크가 불안하다면 원격 `DB` 서버에 접속하다 실패해서 `SQLException`이 발생할 수 있다. 이 경우에 재시도를 해볼 수 있는데, 일정 시간 대기했다가 접속을 시도해보는 방법을 통해 예외상황으로부터 복구를 시도할 수 있다. 물론 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 한다. 아래의 코드는 통제 불가능한 요인으로 인해 예외가 발생하면 `MAX_RETRY`만큼 재시도를 하는 예제다.

```java
int maxretry = MAX_RETRY;
while(maxretry -- > 0) {
    try {
        // ...  // 예외가 발생할 가능성이 있는 시도
        return; // 작업 성공
    }
    catch (SomeException e) {
        // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
        // 리소스 반납. 정리 작업
    }
}
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

### 예외처리 회피

두 번째 방법은 예외를 자신을 호출한 쪽으로 던지는 것이다. `throws` 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 `catch` 문으로 예외를 잡고 로그 등을 남긴 뒤에 다시 예외를 던지는(`rethrow`) 것이다.

예외처리를 회피하려면 아래와 같이 반드시 다른 오브젝트나 메서드가 예외를 처리할 수 있도록 해야 한다.

```java
public void add() throws SQLException {
    // JDBC API
}

public void add() throws SQLException {
    try {
        // JDBC API
    }
    catch(SQLException e) {
        // 로그 출력
        throw e;
    }
}
```

`JdbcContext`나 `JdbcTemplate`이 사용하는 콜백 오브젝트는 모두 `throws SQLException`이 붙어 있는데, `ResultSet`이나 `PreparedStatement` 등을 이용해서 작업하다 발생하는 `SQLException`을 자신이 처리하지 않고 템플릿으로 던져버린다. `SQLException`을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다.

하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 것은 무책임한 책임회피일 수 있다. 만약 `DAO`가 `SQLException`을 던져버리면 `DAO`를 사용하는 서비스 계층이나 웹 컨트롤러에서 과연 제대로 처리할 수 있을까? 아마도 `DAO`에서 던진 `SQLException`을 서비스 계층 메서드가 다시 던지고 , 컨트롤러도 다시 던지도록 선언해서 예외는 그냥 서버로 전달될 것이다.

예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야 한다.

### 예외 전환

마지막 방버은 `예외 전환(exception translation)`을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상 상태로는 만들 수 없기 때문에 메서드 밖으로 예외를 던지는 것이다. 다만, 이 과정에서 발생한 예외를 그대로 던지는 것이 아니라 적절한 예외로 전환해서 던진다.

예외 전환은 보통 두 가지 목적으로 사용된다.

첫 번째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다.

예를 들어 새로운 사용자를 등록할 때 아이디가 같은 사용자가 존재하여 `DB` 에러가 발생하면 `JDBC API`는 `SQLException`을 발생시킨다. 이 경우 `DAO` 메서드가 `SQLException`을 밖으로 던져버리면 서비스 계층 등에서는 왜 `SQLException`이 발생했는지 쉽게 알 방법이 없다. 이럴 때는 `DAO`에서 `SQLException`의 정보를 해석해서 `DuplicateUserIdException` 같은 예외로 바꿔서 던져주는 것이 좋다. 의미가 분명한 예외가 던져지면 서비스 계층 오브젝트에는 적절한 복구 작업을 시도할 수 있다.

아래의 코드는 사용자 정보를 등록하려고 시도해보고, 만약 중복된 아이디 값이 존재하여 에러가 발생한다면 이를 확인해서 의미 있는 `DuplicateUserIdException`으로 전환해주는 예제다.

```java
public void add(User user) throws DuplicateUserIdException, SQLException {
    try {
        // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
        // 그런 기능을 가진 다른 SQLException을 던지는 메서드를 호출하는 코드
    }
    catch(SQLException e) {
        // ErrorCode가 MySQL의  "Duplicate Entry(1062)"이면 예외 전환
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicateUserIdException();
        else
            throw e; // 그 외의 경우는 SQLException 그대로
    }
}
```

보통 전환하는 예외에 원래 발생한 예외를 담아서 `중첩 예외(nested exception)`로 만드는 것이 좋다. 중첩 예외는 `getCause()` 메서드를 이용해서 처음 발생한 예외가 무엇인지 확인할 수 있다. 아래와 같이 새로운 예외를 만들면서 생성자나 `initCause()` 메서드로 근본 원인이 되는 예외를 넣어줄 수 있다.

```java
catch(SQLException e) {
    // ...
    throw DuplicateUserIdException(e);
}

catch(SQLException e) {
    // ...
    throw DuplicateUserIdException().initCause(e);
}
```

두 번째 전환 방법은 예외를 처리하기 쉽고 단순하게 만들기 위해 `포장(wrap)`하는 것이다. 중첩 예외를 이용해 새로운 예외를 만들고 `원인(cause)`이 되는 예외를 내부에 담아서 던지는 방식은 같지만, 의미를 명확하게 하려고 다른 예외로 전환하는 것은 아니다. 주로 예외처리를 강제하는 `체크 예외`를 `언체크 예외`인 `런타임 예외`로 바꾸는 경우에 사용한다.

대표적인 예로 `EJBException`이 있다. `EJB` 컴포넌트 코드에서 발생하는 대부분의 `체크 예외`는 비즈니스 로직으로 볼 때 의미 있는 예외도 아니고 복구 가능한 예외도 아니다. 따라서 아래와 같이 `런타임 예외`인 `EJBException`으로 포장해서 던지는 것이 낫다.

```java
try {
    OrderHome orderHome = EJBHomeFactory.getInstance().getOrderHome();
    Order order = orderHome.findByPrimaryKey(Integer id);
} catch (NamingException ne) {
    throw new EJBException(ne);
} catch (SQLException se) {
    throw new EJBException(se);
} catch (RemoteException re) {
    throw new EJBException(re);
}
```

`EJBException`은 `RuntimeException` 클래스를 상속한 예외다. `런타임 예외`로 만들어서 전달하면 `EJB`는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백해준다. `런타임 예외`이므로 `EJB` 컴포넌트를 사용하는 다른 `EJB`나 클라이언트에서 일일이 예외를 잡거나 던질 필요가 없다. 예외를 잡아도 복구할 수 없기 때문이다.

반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외상황이 발생할 수도 있는데, 이때는 `API`가 던지는 예외가 아니라 애플리케이션 코드에서 의도적으로 던지는 예외다. 따라서 `체크 예외`를 사용하는 것이 적절하다. 비즈니스적인 의미가 있는 예외는 적절한 대응이나 복구 작업이 필요하기 때문이다.

대부분 서버환경에서는 애플리케이션 코드에서 처리하지 않고 전달된 예외들을 일괄적으로 다룰 수 있는 기능을 제공한다. 복구하지 못할 예외라면 애플리케이션 코드에서는 `런타임 예외`로 포장해서 던져버리고, 예외처리 서비스 등을 이용해 자세한 로그를 남기고, 관리자에게는 메일 등으로 통보하고, 사용자에게는 친절한 안내 메시지를 보여주는 것이 바람직하다.

## 4.1.4 예외처리 전략

지금까지 살펴본 예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해보자.

### 런타임 예외의 보편화

자바 엔터프라이즈 서버환경에서는 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다. 독립형 애플리케이션과 달리 서버의 특정 계층에서 예외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션하면서 예외상황을 복구할 수 있는 방법이 없으므로 차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 것이 좋다. 또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청의 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이 낫다.

자바의 환경이 서버로 이동하면서 `체크 예외`의 활용도와 가치는 점점 떨어지고 있다. 그래서 대응이 불가능한 `체크 예외`라면 `런타임 예외`로 전환해서 던지는 것이 낫다.

자바 초기부터 있었던 `JDK`의 `API`와 달리 최근에 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 `API`가 발생시키는 예외를 `체크 예외` 대신 `언체크 예외`로 정의하는 것이 일반화되고 있다.

### add() 메소드의 예외처리

```java
public void add(User user) throws DuplicateUserIdException, SQLException {
    try {
        // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
        // 그런 기능을 가진 다른 SQLException을 던지는 메서드를 호출하는 코드
    }
    catch(SQLException e) {
        // ErrorCode가 MySQL의  "Duplicate Entry(1062)"이면 예외 전환
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicateUserIdException();
        else
            throw e; // 그 외의 경우는 SQLException 그대로
    }
}
```

위에서 작성한 `add()` 메서드는 `DuplicateUserIdException`과 `SQLException` 두 가지 `체크 예외`를 던지게 되어 있다. `SQLException`은 대부분 복구가 불가능하므로 잡아봤자 처리할 수 없으므로 결국 `throws`를 타고 계속 전달되다가 애플리케이션 밖으로 던져질 것이다. 그럴 바에는 `런타임 예외`로 포장해 던져서 그 밖의 메서드들이 신경 쓰지 않도록 하는 것이 낫다.

`add()` 메서드를 수정하기 위해 아래와 같이 `DuplicateUserIdException` 예외를 작성한다. 필요하면 언제든 잡아서 처리할 수 있도록 별도의 예외로 정의하지만, 필요 없다면 신경 쓰지 않아도 되도록 `RuntimeException`을 상속받는다. 중첩 예외를 만들 수 있도록 생성자를 추가해주자.

```java
public class DuplicateUserIdException extends RuntimeException {
    public DuplicateUserIdException(Throwable cause) {
        super(cause);
    }
}
```

이제 `add()` 메서드를 수정하면 되는데, `SQLException`을 `런타임 예외`로 전환해서 던지도록 한다. 코드는 아래와 같다.

```java
public void add() throws DuplicateUserIdException {
    try {
        // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
        // 그런 기능이 있는 다른 SQLException을 던지는 메서드를 호출하는 코드
    }
    catch (SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw new DuplicateUserIdException(e); // 예외 전환
        else
            throw new RuntimeException(e); // 예외 포장
    }
}
```

이제 특별한 의미를 가지는 `DuplicateUserIdException` 외에 시스템 예외에 해당하는 `SQLException`은 `언체크 예외`가 됐다. 따라서 메서드 선언의 `throws`에 포함시킬 필요가 없다. 반면에 역시 `언체크 예외`로 만들어지긴 했지만 `add()` 메서드를 사용하는 쪽에서 아이디 중복 예외를 처리하고 싶은 경우 활용할 수 있음을 알려주도록 `DuplicateUserIdException`을 메서드의 `throws` 선언에 포함시킨다.

이렇게 `런타임 예외`를 일반화해서 사용하는 방법은 여러모로 장점이 많다. 단, `런타임 예외`로 만들었으므로 사용에 더 주의를 기울여야 한다. 컴파일러가 예외처리를 강제하지 않으므로 신경 쓰지 않으면 예외상황을 충분히 고려하지 않을 수 있기 때문이다.

### 애플리케이션 예외

시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 `catch` 해서 무엇인가 조치를 하도록 요구하는 예외도 있다. 이러한 예외들을 `애플리케이션 예외`라고 한다.

예를 들어 사용자가 요청한 금액을 은행계좌에서 출금하는 기능을 가진 메서드가 있다고 가정해보자. 현재 잔고를 확인하고, 허용하는 범위를 넘어서 출금을 요청하면 출금 작업을 중단시키고, 적절한 경고를 사용자에게 보내야할 것이다. 이러한 메서드를 설계하는 방법은 두 가지가 있다.

첫 번째 방법은 정상적인 출금처리를 했을 경우와 잔고 부족이 발생했을 경우에 각각 다른 종류의 리턴 값을 돌려주는 것이다. 리턴 값을 일종의 결과 상태를 나타내는 정보로 활용하는 것이다. 예를 들어 정상적으로 처리된 경우 요청금액 자체를 리턴하고, 잔고가 부족하다면 `0` 또는 `-1` 같은 특별한 값을 리턴한다.

하지만 이렇게 리턴 값으로 결과를 확인하고, 예외상황을 체크하면 불편한 점이 있다. 예외상황에 대한 리턴 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다. 개발자마다 특별한 값을 다르게 생각할 수 있기 떄문이다. 또 한 가지 문제는 결과 값을 확인하는 조건문이 자주 등장한다는 점이다. 즉, 코드는 지저분해지고 흐름을 파악하고 이해하기가 힘들어질 것이다.

두 번째 방법은 정상적인 흐름을 따르는 코드는 그대로 두고, 잔고 부족과 같은 예외상황에서는 비즈니스적인 의미를 띤 예외를 던지도록 하는 것이다. 잔고 부족인 경우라면 `InsufficientBalanceException` 등을 던질 수 있다. 예외상황을 처리하는 `catch` 블럭을 메서드 호출 직후에 둘 필요는 없다. 정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드를 `try` 블럭 안에 정리해두고 예외상황에 대한 처리는 `catch` 블럭에 모아둘 수 있기 때문에 코드를 이해하기도 편하다.

이때 사용하는 예외는 의도적으로 `체크 예외`로 만들어서 개발자가 잊지 않고 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제하는 것이 좋다. 아래의 예제는 예금을 인출해서 처리하는 코드를 정상 흐름으로 만들어두고, 잔고 부족을 `애플리케이션 예외`로 만들어 처리하도록 만든 코드다. `애플리케이션 예외`인 `InsufficientBalanceException`을 만들 때는 예외상황에 대한 상세한 정보를 담고 있도록 설계할 필요가 있다. 잔고가 부족한 경우라면 현재 인출할 수 있는 최대 금액이 얼마인지를 확인해서 예외 정보에 넣어준다면 좋을 것이다.

```java
try {
    BigDecimal balance = account.withdraw(amount);
    // 정상적인 처리 결과를 출력하도록 진행
} catch (InsufficientBalanceException e) { // 체크 예외
    // InsufficientBalanceException에 담긴 인출 가능한 잔고금액 정보를 가져옴
    BigDecimal availFunds = e.getAvailFunds();
    // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
}
```

## 4.1.5 SQLException은 어떻게 됐나?
